server:
  port: 8082
spring:
  application:
    name: consumer2-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://ws:123@localhost:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
info:
  app.name: consumer2-service
  company.name: com.ws
  build.artifactId: $project.artifactId$
  build.version: $project.version$