server:
  port: 8091
spring:
  application:
    name: provider1-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://ws:123@localhost:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
info:
  app.name: provider1-service
  company.name: com.ws
  build.artifactId: $project.artifactId$
  build.version: $project.version$